package foundationdayschedule;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mirza Mohd Aadil Beg
 */
public class RecordForm extends javax.swing.JFrame {

    /**
     * Creates new form RecordForm
     */
    int judgeSession;
    
    public RecordForm(int judge) {
        initComponents();
        judgeSession = judge;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddRecordPanel = new javax.swing.JPanel();
        jMembersLabel = new javax.swing.JLabel();
        jBatchLabel = new javax.swing.JLabel();
        jEventTypeLabel = new javax.swing.JLabel();
        jScoreLabel = new javax.swing.JLabel();
        jAddRecordLabel = new javax.swing.JLabel();
        jMembers = new javax.swing.JTextField();
        jBatch = new javax.swing.JTextField();
        jEventType = new javax.swing.JTextField();
        jScore = new javax.swing.JTextField();
        jAddButton = new javax.swing.JButton();
        jEditPanel = new javax.swing.JPanel();
        jIdLabel = new javax.swing.JLabel();
        jEditScoreLabel = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jEditScore = new javax.swing.JTextField();
        jSaveButton = new javax.swing.JButton();
        jEditLabel = new javax.swing.JLabel();
        jTablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jRecordTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMembersLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jMembersLabel.setText("Memebers");

        jBatchLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jBatchLabel.setText("Batch");

        jEventTypeLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jEventTypeLabel.setText("Event Type");

        jScoreLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jScoreLabel.setText("Score");

        jAddRecordLabel.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jAddRecordLabel.setText("Add Record");

        jAddButton.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jAddButton.setText("Add");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAddRecordPanelLayout = new javax.swing.GroupLayout(jAddRecordPanel);
        jAddRecordPanel.setLayout(jAddRecordPanelLayout);
        jAddRecordPanelLayout.setHorizontalGroup(
            jAddRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAddRecordPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jAddRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScoreLabel)
                    .addComponent(jEventTypeLabel)
                    .addComponent(jBatchLabel)
                    .addComponent(jMembersLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jAddRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jAddButton)
                    .addGroup(jAddRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jMembers, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(jBatch)
                        .addComponent(jEventType)
                        .addComponent(jScore)))
                .addGap(114, 114, 114))
            .addGroup(jAddRecordPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jAddRecordLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jAddRecordPanelLayout.setVerticalGroup(
            jAddRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddRecordPanelLayout.createSequentialGroup()
                .addComponent(jAddRecordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jAddRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMembersLabel)
                    .addComponent(jMembers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jAddRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBatchLabel)
                    .addComponent(jBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jAddRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEventTypeLabel)
                    .addComponent(jEventType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jAddRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jScoreLabel)
                    .addComponent(jScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jAddButton))
        );

        jIdLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jIdLabel.setText("Id");

        jEditScoreLabel.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jEditScoreLabel.setText("Score");

        jSaveButton.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jSaveButton.setText("Save");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        jEditLabel.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jEditLabel.setText("Edit");

        javax.swing.GroupLayout jEditPanelLayout = new javax.swing.GroupLayout(jEditPanel);
        jEditPanel.setLayout(jEditPanelLayout);
        jEditPanelLayout.setHorizontalGroup(
            jEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditPanelLayout.createSequentialGroup()
                .addGroup(jEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSaveButton))
                    .addGroup(jEditPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jIdLabel)
                            .addComponent(jEditScoreLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jEditScore, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(jEditPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jEditLabel)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jEditPanelLayout.setVerticalGroup(
            jEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditPanelLayout.createSequentialGroup()
                .addComponent(jEditLabel)
                .addGap(23, 23, 23)
                .addGroup(jEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jEditPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEditScoreLabel)
                            .addComponent(jEditScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jIdLabel)))
                .addGap(18, 18, 18)
                .addComponent(jSaveButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jRecordTable.setFont(new java.awt.Font("Cantarell", 0, 15)); // NOI18N
        jRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Members", "Batch", "Event", "J1", "J2", "J3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jRecordTable);

        javax.swing.GroupLayout jTablePanelLayout = new javax.swing.GroupLayout(jTablePanel);
        jTablePanel.setLayout(jTablePanelLayout);
        jTablePanelLayout.setHorizontalGroup(
            jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jTablePanelLayout.setVerticalGroup(
            jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addComponent(jTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jAddRecordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAddRecordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        // TODO add your handling code here:
        Database db = new Database();
        db.initConnection();
        int members = Integer.parseInt(jMembers.getText());
        String batch = jBatch.getText();
        String eventType = jEventType.getText();
        int score = Integer.parseInt(jScore.getText());
        db.addRecord(members, batch, eventType, score, judgeSession, this);
        populateTable();
        repaintTable();
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        // TODO add your handling code here:
        Database db = new Database();
        db.initConnection();
        int id = Integer.parseInt(jId.getText());
        int score = Integer.parseInt(jEditScore.getText());
        db.editScore(id, score, judgeSession, this);
        populateTable();
        repaintTable();
    }//GEN-LAST:event_jSaveButtonActionPerformed
    
    private void populateTable() {
        try {
            String records = "select * from records";
            Database db = new Database();
            db.initConnection();
            ResultSet rs = db.getResultSet(records);
            jRecordTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch (Exception e){JOptionPane.showMessageDialog(this, e);}
    }
    
    private void repaintTable() {
        jTablePanel.revalidate();
        jTablePanel.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordForm(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JLabel jAddRecordLabel;
    private javax.swing.JPanel jAddRecordPanel;
    private javax.swing.JTextField jBatch;
    private javax.swing.JLabel jBatchLabel;
    private javax.swing.JLabel jEditLabel;
    private javax.swing.JPanel jEditPanel;
    private javax.swing.JTextField jEditScore;
    private javax.swing.JLabel jEditScoreLabel;
    private javax.swing.JTextField jEventType;
    private javax.swing.JLabel jEventTypeLabel;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jIdLabel;
    private javax.swing.JTextField jMembers;
    private javax.swing.JLabel jMembersLabel;
    private javax.swing.JTable jRecordTable;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JTextField jScore;
    private javax.swing.JLabel jScoreLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jTablePanel;
    // End of variables declaration//GEN-END:variables
}
